version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  cdn:
    image: nginx:alpine
    volumes:
      - ./cdn:/usr/share/nginx/html:ro
    ports:
      - "80:80"