-- src/main/resources/schema.sql

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  locale VARCHAR(5) NOT NULL,
  translation_key VARCHAR(255) NOT NULL,  -- renamed here
  content CLOB NOT NULL,
  tag VARCHAR(50) NOT NULL
);
